### PR TITLE
Add messages for RS Children and CACO compatibility patches

### PR DESCRIPTION
**Pull request by sean-kang**

### CODE REVIEW

**Review by MacSplody — COMMENTED** [review]
Changes are fine, I'd split that up into at least two commits though.
Commits with a `&` or an `and` usually indicate seperate commits should be used.

https://www.freshconsulting.com/atomic-commits/

**Comment by sean-kang** [comment]
I thought it would be squashed like it was before. That's okay. Here are new split commits.

**Comment by MacSplody** [comment]
> 
> 
> I thought it would be squashed like it was before. That's okay. Here are new split commits.

No worries, and thanks.
I try to avoid squashing where possible. I'll generally only squash to tidy up the commits if there are corrections, and all the commits are to the same mod. Make as many commits as you feel you need, within reason of course.

**Review by MacSplody — APPROVED** [review]
Perfect, thanks.

**Pull request merged**
