### PR TITLE
Update Skyrim Alchemy and Food Overhaul

### PR DESCRIPTION
**Pull request by MacSplody**
#1357

### CODE REVIEW

**Review by sibir-ine — COMMENTED** [review]
Just a heads up, I tested SAFO with a bashed patch and the leveled list additions get forwarded just fine, even the multiple entries which WB can sometimes have an issue with. I tested both on its own and with a test plugin to overwrite the additions.

**Comment by MacSplody** [comment]
> Just a heads up, I tested SAFO with a bashed patch and the leveled list additions get forwarded just fine, even the multiple entries which WB can sometimes have an issue with. I tested both on its own and with a test plugin to overwrite the additions.

Maybe it's removing empty sublists, I haven't tested with that turned on yet, either way the level list fix wouldn't be required.

**Comment by MacSplody** [comment]
With remove empty sublists turned on.

image

**Comment by sibir-ine** [comment]
Ah, that option completely slipped my mind. Considering it should only be used if the user knows they don't have any mods using leveled list injectors, they shouldn't be using it with this mod. It's disabled by default for that reason, so most people probably won't run into this problem. Also, the fix will completely overwrite any other changes to those 3 leveled lists, so it's probably best avoided.

**Pull request merged**
