### PR TITLE
Finnish localization

### PR DESCRIPTION
**Pull request by 3ventic**

### CODE REVIEW

**Comment by pStyl3** [comment]
@3ventic Can this be merged?

**Comment by pStyl3** [comment]
Please rebase @3ventic, I've merged [this PR](https://github.com/loot/skyrimse/pull/760) which reorders the translated messages (`fi` should now be inbetween `es` and `fr`) and fixes a problem with the Polish translation.

**Comment by 3ventic** [comment]
It's not ready. I've not had time. I'll mark ready when it's ready.

**Comment by MacSplody** [comment]
@3ventic I've rebased your changes on a new branch https://github.com/loot/skyrimse/tree/rebase-loc-fi

**Comment by pStyl3** [comment]
It would be great if we could do something about this PR. It doesn't seem to me that the provided finnish translations need work on them, rather than that it seems as if @3ventic planned to do more translations, but didn't had the time in order to do so. As such, would speak anything against merging 3ventic's changes ourselves while giving credit to him? If the Finnish localization should get an update at a later date, this could be realized through a new PR then.

**Comment by 3ventic** [comment]
#1594

**Pull request closed without merging**
