### PR TITLE
Update Spell Research Patch Compendium Redux

### PR DESCRIPTION
**Pull request by cecell**
All of the mounts I added are conjurable so I left them under the ###### Gameplay - Magic & Abilities ###### section.  I reordered a few entries that I had submitted before alphabetically as they were out of order.  Thanks y'all

EDIT: The two that I reordered are - name: 'SovngardeSummonables.esp' and - name: 'Tainted_Blood.esp'

### CODE REVIEW

**Review by sibir-ine — CHANGES_REQUESTED** [review]
@cecell, in #2289, I split `&patch3rdParty_SRPC` into `&patch3rdParty_SRPC` & `&patch3rdParty_SRPC_Redux`, `&patch3rdParty_SRPC` being for mods patched by both SRPC & SRPCR & `&patch3rdParty_SRPC_Redux` being for mods only patched by SRPCR. I noticed a few mods in this PR were given `*patch3rdParty_SRPC` messages but are only patched by SRPCR. Can you please correct those?

**Comment by cecell** [comment]
Well crap, I didn't update the formula in my spreadsheet so it pulled the old ok fixing now sorry...

**Comment by cecell** [comment]
The second commit has the corrections requested, sorry for the delay

**Comment by sibir-ine** [comment]
@cecell As I said in Discord, there are a few links with `?tab=files` in them, so those should be removed. There are also a few `msg` keys & `*patch3rdParty_SRPC_Redux` messages that should be sorted alphabetically. I also noticed that you reverted some `*patch3rdParty_SRPC` messages back to `*patch3rdParty_SRPC_Redux` messages even though those mods were covered by both SRPC & SRPCR, so I'm restoring those.

**Review by sibir-ine — APPROVED** [review]

**Comment by sibir-ine** [comment]
@cecell Thanks!

**Pull request merged**
