### PR TITLE
Update RS Children + CRF Patch ESP

### PR DESCRIPTION
**Pull request by ann4belle**
CRF modpage no longer includes patch. Swapped message to patch3rdParty and added link.

### CODE REVIEW

**Review by MacSplody — CHANGES_REQUESTED** [review]
There is also another version included with [RS Children Patch Compendium](https://www.nexusmods.com/skyrimspecialedition/mods/13409) `RSC CRF Patch.esp`

```yaml
      - <<: *patch3rdParty
        subs: 
          - 'RS Children Overhaul' 
          - '[ RS Children Overhaul Cutting Room Floor Patch ](https://www.nexusmods.com/skyrimspecialedition/mods/8753)'
        condition: 'active("RSkyrimChildren.esm") and not active("CRF_RSChildrenPatch.esp") and not file("RSC CRF Patch.esp")'
      - <<: *patch3rdParty
        subs: 
          - 'RS Children Overhaul' 
          - '[ RS Children Patch Compendium ](https://www.nexusmods.com/skyrimspecialedition/mods/13409)'
        condition: 'active("RSkyrimChildren.esm") and not active("RSC CRF Patch.esp") and not file("CRF_RSChildrenPatch.esp")'
```
Above will cover either patch being used, messages will only display if neither patch is present, and only for one mod if patch is present but deactivated.

**Comment by ann4belle** [comment]
```
- <<: *patch3rdParty
  subs: 
    - 'RS Children Overhaul' 
    - '[ RS Children Patch Compendium ](https://www.nexusmods.com/skyrimspecialedition/mods/13409)'
  condition: 'active("RSkyrimChildren.esm") and not active("RSC CRF Patch.esp") and not active("CRF_RSChildrenPatch.esp")'
```
Would it not be better to do this, and link the Compendium for user convenience, while still having support for the other patch?

**Comment by MacSplody** [comment]
I've tried that approach before, it just causes confusion when they have a patch installed but the linked patch for the warning message is different.
There is no harm in having both, you'll see both links if no patch is installed.
Only one message if either is installed but is not active.
So they will see both and can decide which they want to use. You could swap the order to have the compendium message at the top.

**Review by MacSplody — APPROVED** [review]

**Comment by MacSplody** [comment]
👍 Thanks for the contribution @Not-A-Walnut

**Pull request merged**
