### PR TITLE
Even Better Quest Objectives Patch for AS-LAL

### PR DESCRIPTION
**Pull request by Graybark**

### CODE REVIEW

**Review by MacSplody — COMMENTED** [review]
Just my two cents, but this already loads after main plug-in as it's a master, it's also included in main installer, which will detect if Alt start is installed and add it.

**Comment by Graybark** [comment]
True. Sorry about that. Must have been a very old meta edit I did.

**Comment by MacSplody** [comment]
No problem, don't know if you checked but it only failed because of a syntax error.
```
YAMLException: bad indentation of a sequence entry at line 842, column 8:
        url: 
           ^
```

**Comment by Graybark** [comment]
No, I did not check but I still fail to see what is wrong with the syntax.

**Comment by MacSplody** [comment]
- name  missing colon

**Comment by Graybark** [comment]
Oh. Thanks.

**Pull request closed without merging**
