### PR TITLE
Update Rob's Bug Fixes - RedBag's Solitude

### PR DESCRIPTION
**Pull request by robertgk2017**
Updated metadata, and removal of the SPO patch as it is no longer needed.

### CODE REVIEW

**Comment by robertgk2017** [comment]
Oof, thats the wrong CRC

should be

      - crc: 0xB9B5FB6A

**Comment by sibir-ine** [comment]
I double-checked the file as downloaded from your page, & you appear to have gotten the checksum right the first time.

**Comment by robertgk2017** [comment]
Thats the crc of the file before i uploaded it though :(

**Comment by robertgk2017** [comment]
just re- ran it on my end its.  
      - crc: 0xB9B5FB6A

did nexus bork on me on its stupid caching thing?  let me re-upload it.

**Comment by robertgk2017** [comment]
Oh yea, nexus is screwing it up.  the file im uploading is not the file its presenting on the files tab.  Hang on let me ping on Picky.

**Review by sibir-ine — APPROVED** [review]
I see, thanks for clarifying; I'll take your word for it then. Thanks!

**Pull request merged**
