### PR TITLE
Update masterlist.yaml

### PR DESCRIPTION
**Pull request by ghost**
More Idle Markers is now made as a compatibility version and is to be loaded above other mods, including Immersive Citizens.

### CODE REVIEW

**Comment by Ortham** [comment]
Thanks! 👍

**Comment by ghost** [comment]
Are circular leveled lists something you want reported in LOOT?

**Comment by MacSplody** [comment]
@bpipher0225 It may be worth looking at since they can crash the game. Have you found one?

**Comment by ghost** [comment]
@CptMcSplody Yes there's one in Skyrim Immersive Creatures (v6.6a) at _00GiantWeaponFire and one in Unique Loot (v05-23-18) at AAAA_WoodPileSmallLl 

Skyrim Immersive Creatures: https://www.nexusmods.com/skyrimspecialedition/mods/12680/?tab=files
(Skyrim Immersive Creatures.esp)

Unique Loot: https://www.nexusmods.com/skyrimspecialedition/mods/734?tab=files
(mrbs-uniqueloot-se.esp)

Let me know if you do a commit for these, I'll look how you formatted it so I can report any others or update if those get hotfixed as I've made  bug reports on the mods.

**Comment by MacSplody** [comment]
@bpipher0225 Skyrim Immersive Creatures one should be fine as its a new entry & nothing references it.
Unique Loot - I'm not sure on that, I thought the woodpiles feature was removed.
I see you have informed the authors, we can wait for a reply anyway.

**Pull request merged**
