### PR TITLE
Update Improved Closefaced Helmets - Fixes

### PR DESCRIPTION
**Pull request by sibir-ine**

### CODE REVIEW

**Comment by loicreynier** [comment]
I am confused on how version metadata works in those conditions. The "missing USSEP patch" message is back while using the Fixes plugin after these changes.

**Comment by sibir-ine** [comment]
Update to v1.2 or higher if available, it was added there.

**Comment by loicreynier** [comment]
Oh right I did not understand that the version was parsed from the ESP.

**Comment by sibir-ine** [comment]
Correct, it's parsed from the plugin's description.

**Pull request merged**
