### PR TITLE
Swap Before/After for IC

### PR DESCRIPTION
**Pull request by Spu00Key**

### CODE REVIEW

**Comment by Ortham** [comment]
You just added these in PR #18, now you're changing them, so soon after. Why didn't you catch these when you made PR #18? I don't know what's right or wrong with the metadata, I'm relying on you to know what you're doing is right, so it's a bit disconcerting to see this.

**Comment by Spu00Key** [comment]
It's a mind short circuit type thing.  These updates I post are indeed reflected by author notes or personal experience.  The issue I keep having issues with is the Load After attribute.
- So with PR #18, the author for the two mods changed updated their information to say load this mod before IC.
- When converting into LOOT I should not touch those two mods, but instead add them to IC's load after list.
- So my mind is really running into issues with the inverted action on an inverted plugin.
- I'll be adding an additional mental check with the help of excel.

I have it set up now to convert Load Before into a Load After since that is really tripping up my mind.

**Comment by Ortham** [comment]
So you're sure this is now the correct metadata? I'd double-check, but I don't know where you're sourcing it from.

**Comment by Spu00Key** [comment]
I've included the below information / links for you to double-check.


[Darkwater Crossing Load Order](http://www.nexusmods.com/skyrimspecialedition/mods/326/?)

> LOOT should be used for optimal placement.
> 
> This mod must load after Skyrim Bridges or the landscape and navmesh changes will be wiped out and the NPCs will not be able to access their homes.
> 
> This mod must also load AFTER Immersive Citizens - AI Overhaul or the navmesh data will be overridden in areas where the new buildings have been added and the NPCs will be unable to navigate properly.

[Whistling Mine Load Order](http://www.nexusmods.com/skyrimspecialedition/mods/367/?)

> LOOT should be used for optimal placement.
> 
> This mod must also load AFTER Immersive Citizens - AI Overhaul. Changes made to the NPC references will be lost otherwise and they will not behave properly.

[IC Load Order](http://www.nexusmods.com/skyrimspecialedition/mods/173/?)

> - The main plugin (Immersive Citizens - AI Overhaul.esp) must be positioned above (or must be loaded before):
> DynDOLOD
> ELFXEnhancer (from Enhanced Lights and FX)
> Enhanced Lighting for ENB
> More Tavern Idles
> Provincial Courier Service
> Relationship dialogue overhaul
> The provided compatibility patches
> 
> - The main plugin (Immersive Citizens - AI Overhaul.esp) must be positioned below (or must be loaded fater): 
> any plugin which edits Breezehome, Honeyside, Vlindrel, Hall Hjerim or Proudspire Manor
> Breezehome by Elianora
> Civil War Repairs
> Enhanced Skyrim Factions - The Companions Guild
> Immersive Content - Realistic Outdoor Lights
> Interesting NPCs
> Requiem
> Routa - Stormcloak and Warrior cabin
> Skyfall Estate (SE)
> Skyrim Bridges

**From the author in a PM:**

> Hi maddbomber83,
> 
> 
> I noticed that you added the following informations related to Immersive Citizens in the masterlist for SkyrimSE.
> 
> Quote
> + - name: 'Darkwater Crossing.esp'
> + after:
> 
> + - 'Immersive Citizens - AI Overhaul.esp'
> 
> 
> 
> + - name: 'Whistling Mine.esp'
> + after:
> 
> + - 'Immersive Citizens - AI Overhaul.esp'
>  
> These rules are incorrects.
> Concerning Darkwater Crossing.esp, the load order does not matter anymore since more than 1 year because there is no conflict anymore. It's easy to check this by using TES5edit.
> Concerning Whistling Mine.esp, there is no optimal load order due to 3 conflicts with this mod which must be resolved through a compatibility patch. Indeed:
> - If you load Whistling Mine.esp after Immersive Citizens - AI Overhaul.esp when you start a new game or when you reboot Immersive Citizens, then 3 NPCs living in Whistling Mine won't be affected by Immersive Citizens.
> - If you load Immersive Citizens - AI Overhaul.esp after Whistling Mine.esp, then 3 NPCs living in Whistling Mine won't sleep inside their new house.
> Therefore these rules should be removed because they are incorrects.
> Feel free to add a compatibility note concerning Whistling Mine.esp and Immersive Citizens - AI Overhaul.esp.

**Comment by Spu00Key** [comment]
Bah, the mind is still playing tricks...  I read these to be correct by the first change from Arthmoor where he says to load AFTER IC.

But the author of IC is contradicting in a PM.  So I should now have these two authors contact each other to resolve.

If my mind is not playing tricks, I would like close this PR and submit a new one based on the posted Load Orders (from descriptions).  I will facilitate Arthmoor and Shurah to communicate on their differences.

Do you read the same?

**Comment by Ortham** [comment]
@Arthmoor: It seems that there's some confusion over compatibility between a couple of your mods and Immersive Citizens. Are their Nexus page descriptions just outdated as Shurah suggests?

**Comment by Spu00Key** [comment]
I've had a lengthy conversation with IC and sent a Nexus PM to Arthmoor.

**Comment by Arthmoor** [comment]
There's no confusion. Darkwater Crossing and Whistling Mine need to be handled as I've indicated. The descriptions are NOT outdated as has been implied. I don't want to drag the drama involved with the IC author into this, but suffice it to say that much of his "necessary" positioning is largely unnecessary due to how it processes AI through aliases - which are load order agnostic. Navmeshes are not so critical that he needs to have his mod listed so far down the load order the way he keeps saying. Village mods need priority regardless because many of them add new buildings his navmeshes can't account for.

**Pull request closed without merging**
