### PR TITLE
Location updates

### PR DESCRIPTION
**Pull request by MacSplody**

### CODE REVIEW

**Comment by Ortham** [comment]
For future reference, how did you determine the load after / inc metadata?

**Comment by MacSplody** [comment]
https://www.nexusmods.com/skyrimspecialedition/mods/18135

Some of the mod pages have it listed in there description as well.

**Comment by Ortham** [comment]
OK.

**Comment by MacSplody** [comment]
I thought I had it in the original issues post, must have not saved it.

Edit: Updated issue #197  to include the source.

**Pull request merged**
