### PR TITLE
 Add German localization

### PR DESCRIPTION
**Pull request by ghost**
Also fix minor mistakes in the English strings where encountered
Squashed with the bugfixes

### CODE REVIEW

**Comment by ghost** [comment]
Oh god in order to squash inside a pull request I have to rebase,
I am so dumb, git can be so unintuitive.
Please bear with me.

**Comment by Ortham** [comment]
Thanks 👍

**Comment by Ortham** [comment]
> Oh god in order to squash inside a pull request I have to rebase,

It's OK, we can squash commits when we merge the pull request, which is what I've done.

**Comment by ghost** [comment]
Or that.

**Pull request merged**
