### PR TITLE
Update tags for Cutting Room Floor

### PR DESCRIPTION
**Pull request by sibir-ine**
* Removed tags already in plugin description
* Invent is in description, added Invent.Add & Invent.Remove in case author wants to update & replace deprecated tags (#1357)
* Removed unnecessary tags (Actors.DeathItem & C.RecordFlags) in description
* Added EffectStats, EnchantmentStats, Outfits.Add, Outfits.Remove, & SpellStats

### CODE REVIEW

**Review by MacSplody — APPROVED** [review]

**Comment by MacSplody** [comment]
@sibir-ine Thanks.

**Comment by Arthmoor** [comment]
Referencing the comment in #1542 I already made changes to the tags in the last release:

Actors.ACBS, Actors.AIData, Actors.AIPackages, Actors.CombatStyle, Actors.Spells, Actors.Stats, C.Location, C.Owner, C.Regions, Delev, EffectStats, EnchantmentStats, Factions, Graphics, Invent.Add, Invent.Remove, Keywords, NPC.Class, Names, Outfits.Add, Outfits.Remove, SpellStats, Stats, Text

is the current set, which I had to move to a text file in the Data\BashTags folder because it's now too large for the description field.

**Comment by MacSplody** [comment]
> is the current set, which I had to move to a text file in the Data\BashTags folder because it's now too large for the description field.

Right, we'll have to check those for tags manually as LOOT doesn't know about them.

**Comment by Ortham** [comment]
> Right, we'll have to check those for tags manually as LOOT doesn't know about them.

The bash tags LOOT knows about are sourced from the masterlist's `bash_tags` array.

**Comment by MacSplody** [comment]
> 
> 
> > Right, we'll have to check those for tags manually as LOOT doesn't know about them.
> 
> The bash tags LOOT knows about are sourced from the masterlist's `bash_tags` array.

It compares against the header of the plugins is more what I meant.
So you'll know what tags are being applied overall.
It won't check against these files stored in `Data\BashTags` so you won't see them in LOOT.

**Comment by Arthmoor** [comment]
It might be something to consider writing up support for if more mod authors start adding their tag lists. That description field is limited to 512 chars and a tag list eats that up fast. These external files may end up getting used more.

**Comment by Ortham** [comment]
> It won't check against these files stored in `Data\BashTags` so you won't see them in LOOT.

Ah, I see. In that case it might be worth adding support for `Data\BashTags` then, as Arthmoor says.

**Comment by Infernio** [comment]
See [this comment](https://github.com/loot/loot/issues/1408#issuecomment-770201701), we need to have a discussion about the future of these files.

**Pull request merged**
