### PR TITLE
Translated the text into Japanese.

### PR DESCRIPTION
**Pull request by tktk11**
I translate all the untranslated sentences into Japanese. This is my first pull request, so please let me know if there is a mistake.

### CODE REVIEW

**Comment by MacSplody** [comment]
There's just some trailing whitespace after a few lines, that should be removed.
The rest looks good.

image

**Review by MacSplody — CHANGES_REQUESTED** [review]
Just remove the trailing whitespace on lines 54, 90, 103, 149, and 177.
The rest is perfect.

**Comment by tktk11** [comment]
I just remove whitespace.

**Review by MacSplody — APPROVED** [review]

**Comment by MacSplody** [comment]
@tktk11 Thanks. 👍

**Pull request merged**
